add Metricly sink
metricly/heapster pull request #1
Opened 2018-03-09 14:44 UTC by yahonggu

**What this PR does**

2018-03-09 14:54 UTC, TheConnMan requested changes

2018-03-09 14:54 UTC, TheConnMan commented on common/metricly/metricly.go
> +		ApiURL: "https://api.app.netuitive.com/ingest",
`https://api.app.metricly.com/ingest`

2018-03-09 14:54 UTC, TheConnMan commented on metrics/sinks/metricly/metricly.go
> +	glog.Info("Create metricly sink using config: ", config)
Metricly should be capitalized.

2018-03-09 14:54 UTC, TheConnMan commented on metrics/sinks/metricly/metricly_test.go
> +		t.Errorf("element has wrong numbe of tags")
`number` is misspelled.

2018-03-09 14:54 UTC, TheConnMan commented on metrics/sinks/metricly/metricly_test.go
> +		t.Errorf("element has wrong numbe of tags")
This is also missing a "the".

> Element has the wrong number of tags

or better yet

> The element has the wrong number of tags

2018-03-09 14:54 UTC, TheConnMan commented on metrics/sinks/metricly/metricly_test.go
> +		t.Errorf("element has wrong number of metrics")
Same with these

2018-03-09 16:18 UTC, yahonggu commented on common/metricly/metricly.go
> +		ApiURL: "https://api.app.netuitive.com/ingest",
nice catch, I've search both go-client and this repo, there're no longer netuitive mentioned anywhere in the code

2018-03-09 19:16 UTC, TheConnMan commented on metrics/sinks/metricly/metricly.go
> +	glog.Info("Start exporting data batch to metricly ...")
Metricly should be capitalized.

2018-03-09 19:16 UTC, TheConnMan commented on metrics/sinks/metricly/metricly.go
> +func (sink *MetriclyMetricsSink) ExportData(batch *core.DataBatch) {
How large are these data batches? Trying to get an idea of how large the payloads will be and how often they'll come into API.

Additionally, is this a sync call to the sink from something else? Will a slowdown in a Metricly HTTP call cause downstream issues for a K8 cluster?

2018-03-12 13:59 UTC, yahonggu commented on metrics/sinks/metricly/metricly.go
> +func (sink *MetriclyMetricsSink) ExportData(batch *core.DataBatch) {
we're batching on number of elements (20 by default) per payload and send in parallel and the batch size is configurable. On average each element has about <20 metrics.

the caller of ExportData is a sync call and won't call the next Export until the current call returned.

2018-03-12 14:04 UTC, TheConnMan commented on metrics/sinks/metricly/metricly.go
> +func (sink *MetriclyMetricsSink) ExportData(batch *core.DataBatch) {
So high latency in the Metricly API or a large number of serial batched API calls could impact someones additional monitoring of K8?

2018-03-12 14:13 UTC, yahonggu commented on metrics/sinks/metricly/metricly.go
> +func (sink *MetriclyMetricsSink) ExportData(batch *core.DataBatch) {
No, I mean the call our sink is synced/blocking call. I don't think the call to multiple sinks are sequential.

2018-03-12 14:15 UTC, TheConnMan commented on metrics/sinks/metricly/metricly.go
> +func (sink *MetriclyMetricsSink) ExportData(batch *core.DataBatch) {
Ok, that's what I was concerned about. Thanks.

2018-03-13 14:49 UTC, TheConnMan approved these changes

2018-03-13 15:01 UTC, merged